version: "3.9"

services:
  app:
    ports:
      - 3000:3000
    image: hanaonethecar
    build:
      context: packages/app
      dockerfile: Dockerfile
    volumes:
      - ./packages/app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env
