version: "3.9"

services:
  # app:
  #   ports:
  #     - 3000:3000
  #   image: hanaonethecar
  #   build:
  #     context: packages/app
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./packages/app:/usr/src/app
  #     - /usr/src/app/node_modules
  #     - /usr/src/app/.next
  #   env_file:
  #     - .env
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
