import Head from 'next/head'
import cx from "classnames";
import { Disclosure } from '@headlessui/react'
import { UilAngleDown } from '@iconscout/react-unicons'
import { UilAngleRightB } from '@iconscout/react-unicons'

// components
import Layout from '~/components/Layout';
import Card from "~atom/Card";
import style from "./index.module.scss";
import List from "~atom/List";

const index = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section>
          <div className="container">
            <div className={cx('gap-x-[9px] bg-[#f4f7f8] rounded-[20px] grid')}>
              <Card>
                <div className="grid">
                  <div className='pt-[15px] text-[2rem] font-bold text-primary'>오토론</div>
                  <div className='mt-[20px] text-[1.2rem]'>
                    하나카드 없이<br />
                    #빠르게<br />
                    #간편하게<br />
                    #신차구입
                  </div>
                  <div className="col-[2] row-[1_/_span_3]">
                    <img src="/img/img-hanacard-2.webp"
                      srcSet="/img/img-hanacard-2@2x.webp 2x,
                              /img/img-hanacard-2@3x.webp 3x"
                      alt=""
                    />
                  </div>
                  <div className="col-span-2 my-[25px] h-px w-[20px] bg-[#1f1f1f]"></div>
                  <div className='col-span-2'>
                    <div className='text-[1.4rem] font-bold text-highlighted shadow-primary'>
                      대출한도 최대 1억원<br />
                      국산차 수입차 전 차종 넉넉한 대출한도
                    </div>
                  </div>
                  <div className='col-span-2 my-[25px] h-px bg-[#dbdbdb]'></div>
                  <div className='col-span-2'>
                    <div className='text-[1.1rem] text-black'>고정금리</div>
                    <div className='text-[2.2rem] text-[#ee4467] font-bold'>연 3.6%</div>
                  </div>
                  <div className='col-span-2 my-[30px]'>
                    <button className='bg-primary p-[15px] w-full rounded-full text-[1.6rem] text-white font-semibold'>한도 조회 하기</button>
                  </div>
                  <div className='col-span-2'>
                    <div className='text-[1.2rem] font-bold'>빠르고 간편한 내 차 구매 프로세스</div>
                    <List className='mt-[10px] grid grid-cols-2 gap-y-[10px]'>
                      <li>차량선택</li>
                      <li>모바일한도조회</li>
                      <li>전문상담원 안내</li>
                      <li>혜택받고 결제하기</li>
                      <li>구매차량 등록</li>
                    </List>
                  </div>
                  <div className='col-span-2 flex mt-[23px]'>
                    <div>
                      <div className='text-[1.2rem] font-bold'>자동차금융 상담센터</div>
                      <div className='text-[#666] font-light'>평일 09:0~ 18:00</div>
                    </div>
                    <div className='ml-auto text-[1.8rem] text-primary self-center font-thin'>1800-1221</div>
                  </div>
                </div>
              </Card>
              <div className='px-[30px] py-[22px] text-[#333]'>
                [2022.01.04 현재] 기준금리(금융채 6개월) 1.594% + 가산금리 3.300% - 부수거래 감면금리 0.9%* - 우대금리 0.1%**<br />
                *부수거래항목(급여이체(0.3%), 주택청약종합저축납입(0.2%), 제휴카드결제(0.1%), 적금상품납입(0.1%), 하나원큐이체(0.1%), 기타자동이체(0.1%))<br />
                **우대금리항목(콜센터신청or딜러소개(0.1%))
              </div>
            </div>
          </div>
        </section>
        <section className='mt-[10px]'>
          <div className="container">
            <div className="w-full">
              <div className="mx-auto w-full max-w-md rounded-[20px] bg-white">
                <div className="rounded-[20px] border border-[#ccc]">
                  <Disclosure>
                    {({ open }) => (
                      <>
                        <Disclosure.Button className={cx("flex items-center w-full justify-between py-[20px] pl-[30px] pr-[10px] text-left text-[1.4rem] font-bold focus:outline-none", { 'border-b border-[#ccc]': open })}>
                          <span>유의사항</span>
                          <UilAngleDown className={cx({ 'rotate-180 transform': open }, 'h-[30px] w-[30px] text-black')} />
                        </Disclosure.Button>
                        <Disclosure.Panel className="p-[30px] text-sm text-gray-500 prose">
                          <ul>
                            <li>오토할부 이용 고객의 경우 카드별 기본 서비스로 제공되는 포인트, 캐쉬백, 마일리지, 청구할인 등은 중복 적용되지 않습니다.</li>
                            <li>자세한 사항은 자동차금융 상담센터(1800-1221)로 문의 주시기 바랍니다.</li>
                            <li>상품 신청 전 상품설명서 및 약관을 반드시 확인하시기 바랍니다.</li>
                            <li>대출 시점에 신용도 변경에 따라 한도가 변경될 수 있으며 신청이 제한될 수 있습니다.</li>
                            <li>중도상환 시 잔여대출기간에따라 상환원금의 2% 이내로 중도상환수수료가 발생합니다.</li>
                            <li>금리인하요구권 및 대출계약 철회권에 대한 자세한 사항은 홈페이지에서 확인하시기 바랍니다.</li>
                            <li>대출취급이 부적정한 경우 대출이 제한될 수 있습니다.</li>
                            <li>분할상환금(원리금균등)과 이에 수반되는 모든 수수료를 지정된 대금 결제일에 상환합니다.</li>
                            <li>해당 상품은 취급수수료가 없습니다.</li>
                            <li>금융소비자는 해당 상품에 대하여 설명을 받을 권리가 있으며, 그 설명을 듣고 내용을 충분히 이해한 후 거래하시기 바랍니다.</li>
                            <li>연체이자율은 [약정이자율 +3%]이며, 법정 최고금리(20%) 이내에서 적용됩니다.</li>
                            <li>상환능력에 비해 대출금이 과도할 경우, 귀하의 신용등급 또는 개인신용평점이 하락할 수 있습니다.</li>
                            <li>신용등급 또는 개인신용평점 하락 시 금융거래와 관련된 불이익이 발생할 수 있습니다.</li>
                            <li>일정기간 원리금을 연체할 경우, 모든 원리금을 변제할 의무가 발생할 수 있습니다,</li>
                          </ul>
                        </Disclosure.Panel>
                      </>
                    )}
                  </Disclosure>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className='mt-[25px]'>
          <button className='flex gap-x-[10px] p-[18px] w-full bg-[#ee4467] text-center text-white text-[1.6rem] items-center justify-center font-bold'>
            <span>대출 신청 및 약정안내</span>
            <UilAngleRightB />
          </button>
        </section>
      </Layout>
    </>
  );
};

export default index;
