import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '~/components/Layout';
import Home from '~/components/template/Home';


const index: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Home />
      </Layout>
    </>
  )
}

export default index
