import type { NextPage } from 'next'
import Head from 'next/head'
import Home from '~/components/template/Home';


const index: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="absolute"></header>
      <main className="pt-[60px]">
        <Home />
      </main>
      <footer>
      </footer>
    </>
  )
}

export default index
