import type { NextPage } from 'next'
import Head from 'next/head'
import { gql, useQuery } from '@apollo/client';

// components

import Layout from '~/components/Layout';
import Home from '~/components/template/Home';

const HomePage: NextPage = () => {
  const { data, loading, error } = useQuery(gql`
    query {
      ok
    }
  `);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :( {error.message}</p>;

  console.log(data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Home />
      </Layout>
    </>
  )
}

export default HomePage
